version: "3.8"

services:
  db:
    image: postgres:16
    container_name: the_scent_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: scent_user
      POSTGRES_PASSWORD: StrongPass1234
      POSTGRES_DB: scent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

